version: "3"
services:
  # Developer container
  dev:
    # image: osrf/ros:rolling-desktop-full
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile

    environment:
      DISPLAY: "host.docker.internal:0"

    # Change to your container name
    container_name: mobile_robotics_ws
    network_mode: host
    volumes:
      # Mount the project
      - mobile_robotics_volume:/mobile_robotics_ws

    # Default command so things don't shut down after the process ends.
    command: sleep infinity

    # [Optional] Required for ptrace-based debuggers like C++, Go, and Rust
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

volumes:
  mobile_robotics_volume:
