# Usage:
#
# To build the images:
#   docker compose build
#
# To start up a specific service by name:
#   docker compose up <service_name>
#
# To open an interactive shell to a running container:
#   docker exec -it <container_name> bash

version: "3.9"
services:
  # Developer container
  dev:
    # image: osrf/ros:rolling-desktop-full
    build: .

    # Change to your container name
    container_name: mobile_robotics_ws
    volumes:
      # Mount the project
      - ..:/mobile_robotics_ws/:rw

    # Default command so things don't shut down after the process ends.
    command: sleep infinity

    # [Optional] Required for ptrace-based debuggers like C++, Go, and Rust
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
  # Runs any launch configuration in a Docker container (sim etc)
  #sim:
  #  extends: overlay
  #  command: ros2 launch turtlebot3_gazebo turtlebot3_world.launch.py
