@startuml

!theme sunlust

abstract class BaseKnowledgeServer {
  + BaseKnowledgeServer(std::shared_ptr<BaseRobotCommsModel> robot_model, std::shared_ptr<INetworkFactory> network_factory)
  + {abstract} void start()
  + {abstract} void stop()

  # std::shared_ptr<BaseRobotCommsModel> _robot_model
  # std::shared_ptr<INetworkFactory> _network_factory
}

abstract class BaseKnowledgeClient {
  + BaseKnowledgeClient(EpuckNeighbourPacket neighbour, std::function<bool()> running, std::shared_ptr<BaseRobotCommsModel> robot_model, std::shared_ptr<INetworkFactory> network_factory)
  + {abstract} void start()
  + {abstract} void stop()

  # EpuckNeighbourPacket _neighbour
  # {field} std::function<bool()> _running
  # std::shared_ptr<BaseRobotCommsModel> _robot_model
  # std::shared_ptr<INetworkFactory> _network_factory
}

abstract class BaseRobotCommsModel {
  + uint16_t robot_id
  + std::string manager_host
  + uint16_t manager_port
  + std::string robot_command_host
  + uint16_t robot_command_port
  + std::string robot_knowledge_host
  + uint16_t robot_knowledge_exchange_host
  - std::map<uint16_t, EpuckKnowledgeRecord> known_ids
  - Centroid centroid
  - Boundary boundary
  - uint16_t seq

  + BaseRobotCommsModel(...)
  + {abstract} void start()
  + {abstract} void stop()
  + uint16_t get_seq()
  + EpuckKnowledgeRecord* known_ids_begin()
  + EpuckKnowledgeRecord* known_ids_end()
  + size_t known_ids_size()
  + size_t insert_known_ids(EpuckKnowledgeRecord *begin, EpuckKnowledgeRecord *end)
  + EpuckKnowledgePacket create_knowledge_packet()
  + void set_centroid(Centroid centroid)
  + void set_boundary(Boundary boundary)
  + Centroid get_centroid()
  + Boundary get_boundary()
  + uint16_t get_seq()
  + EpuckKnowledgePacket create_knowledge_packet()
  - EpuckKnowledgeRecord update_record()
}

abstract class INetworkFactory {
  + {abstract} std::shared_ptr<IIoContext> create_io_context()
  + {abstract} std::shared_ptr<ITcpSocket> create_tcp_socket(IIoContext &io_context)
  + {abstract} std::shared_ptr<IUdpSocket> create_udp_socket(IIoContext &io_context)
  + {abstract} std::shared_ptr<IResolver> create_resolver(IIoContext &io_context)
  + {abstract} std::shared_ptr<ITimer> create_timer(IIoContext &io_context)
  + {abstract} std::shared_ptr<ITCPEndpoint> create_tcp_endpoint()
  + {abstract} std::shared_ptr<ITCPEndpoint> create_tcp_endpoint(asio::ip::address_v4 addr, uint16_t port)
  + {abstract} std::shared_ptr<IUDPEndpoint> create_udp_endpoint()
  + {abstract} std::shared_ptr<IUDPEndpoint> create_udp_endpoint(asio::ip::address_v4 addr, uint16_t port)
}

class NetworkFactory {
  + std::shared_ptr<IIoContext> create_io_context()
  + std::shared_ptr<ITcpSocket> create_tcp_socket(IIoContext &io_context)
  + std::shared_ptr<IUdpSocket> create_udp_socket(IIoContext &io_context)
  + std::shared_ptr<IResolver> create_resolver(IIoContext &io_context)
  + std::shared_ptr<ITimer> create_timer(IIoContext &io_context)
  + std::shared_ptr<ITCPEndpoint> create_tcp_endpoint()
  + std::shared_ptr<ITCPEndpoint> create_tcp_endpoint(asio::ip::address_v4 addr, uint16_t port)
  + std::shared_ptr<IUDPEndpoint> create_udp_endpoint()
  + std::shared_ptr<IUDPEndpoint> create_udp_endpoint(asio::ip::address_v4 addr, uint16_t port)
}

struct EpuckHeartbeatPacket {
  +{static} uint8_t ID
  +uint16_t robot_id
  +std::array<char, MAX_HOST_LEN + 1> robot_command_host
  +uint16_t robot_command_port
  +std::array<char, MAX_HOST_LEN + 1> robot_knowledge_host
  +uint16_t robot_knowledge_exchange_port
}

struct EpuckNeighbourPacket {
  +{static} uint8_t ID
  +uint16_t robot_id
  +std::array<char, MAX_HOST_LEN + 1> host
  +uint16_t port
  +float distance
}

struct EpuckHeartbeatResponsePacket {
  +{static} uint8_t ID
  +uint8_t num_neighbours
  +std::array<EpuckNeighbourPacket, MAX_ROBOTS> neighbours
}

struct Centroid {
  +float x
  +float y
  +float z
}

struct Boundary {
  +std::array<float, MAX_BOUNDARY_X_POINTS> x_points
  +std::array<float, MAX_BOUNDARY_Y_POINTS> y_points
  +std::array<float, MAX_BOUNDARY_Z_POINTS> z_points
}

struct EpuckKnowledgeRecord {
  +uint16_t robot_id
  +Centroid centroid
  +Boundary boundary
  +uint16_t seq
}

struct EpuckKnowledgePacket {
  +{static} uint8_t ID
  +uint16_t robot_id
  +uint16_t seq
  +uint8_t N
  +std::array<EpuckKnowledgeRecord, MAX_ROBOTS> known_ids
}

struct EpuckCommandPacket {
  +{static} uint8_t ID
  +uint8_t command
  +std::array<uint8_t, 8> data
}


class RobotCommsModel <T : BaseKnowledgeServer\nU : BaseKnowledgeClient> {
  + RobotCommsModel<T, U>(...)
  + void start()
  + void stop()
  - void launch_exchange_heartbeats()
  - void exchange_heartbeats()
  - void launch_handle_commands()
  - void handle_commands()

  - bool _running
  - T* _knowledge_server
  - std::map<uint16_t, U> _knowledge_clients
  - std::thread _exchange_heartbeats_thread
  - std::thread _handle_commands_thread
  - std::shared_ptr<INetworkFactory> _network_factory
  - std::shared_ptr<IIoContext> _io_context
  - std::shared_ptr<IUdpSocket> _command_request_socket
  - {static} char* TAG
}


class UDPKnowledgeServer <T : BaseRobotCommsModel> {
  + UDPKnowledgeServer(std::shared_ptr<T> robot_model, std::shared_ptr<INetworkFactory> network_factory)
  + void start()
  + void stop()
  - void launch_receive_knowledge()
  - void receive_knowledge()
  - void handle_knowledge_packet(IUDPEndpoint &client, std::array<uint8_t, sizeof(EpuckKnowledgePacket)> &data)

  - bool _running
  - std::thread _receive_knowledge_thread
  - std::shared_ptr<IIoContext> _io_context
  - std::shared_ptr<IUdpSocket> _knowledge_server_socket
  - {static} char* TAG
}

class UDPKnowledgeClient <T : BaseRobotCommsModel> {
  + UDPKnowledgeClient(EpuckNeighbourPacket neighbour, std::function<bool()> running, std::shared_ptr<BaseRobotCommsModel> robot_model, std::shared_ptr<INetworkFactory> network_factory)
  + void start()
  + void stop()
  - void launch_send_knowledge()
  - void send_knowledge()

  - bool _stopping
  - std::thread _send_knowledge_thread
  - std::shared_ptr<IIoContext> _io_context
  - std::shared_ptr<IUdpSocket> _knowledge_client_socket
  - {static} char* TAG
}


class GZKnowledgeServer <T : BaseRobotCommsModel> {
  + GZKnowledgeServer(std::shared_ptr<T> robot_model, std::shared_ptr<INetworkFactory> network_factory)
  + void start()
  + void stop()
  - void on_knowledge(const gz_msgs::Dataframe &msg)
  - gz_transport::Node node
  - gz_transport::Publisher pub_knowledge
  - bool running_
  - {static} char* TAG
}

class GZKnowledgeClient <T : BaseRobotCommsModel> {
  + GZKnowledgeClient(EpuckNeighbourPacket neighbour, std::function<bool()> running, std::shared_ptr<T> robot_model, std::shared_ptr<INetworkFactory> network_factory)
  + void start()
  + void stop()
  - void send_knowledge()
  - gz_transport::Node node
  - gz_transport::Publisher pub_knowledge
  - std::thread thread_
  - {static} char* TAG
}


BaseRobotCommsModel <|-- RobotCommsModel
BaseKnowledgeServer <|-- UDPKnowledgeServer
BaseKnowledgeClient <|-- UDPKnowledgeClient
BaseKnowledgeServer <|-- GZKnowledgeServer
BaseKnowledgeClient <|-- GZKnowledgeClient

INetworkFactory <|.. NetworkFactory

EpuckCommandPacket -- RobotCommsModel
EpuckHeartbeatPacket -- RobotCommsModel
EpuckHeartbeatResponsePacket -- RobotCommsModel
EpuckKnowledgePacket o-- EpuckKnowledgeRecord
EpuckHeartbeatResponsePacket o-- EpuckNeighbourPacket

EpuckKnowledgeRecord <-- Centroid
EpuckKnowledgeRecord <-- Boundary

Centroid --> BaseRobotCommsModel
Boundary --> BaseRobotCommsModel

INetworkFactory <.. RobotCommsModel
RobotCommsModel <--> BaseKnowledgeServer
RobotCommsModel *--> BaseKnowledgeClient

EpuckNeighbourPacket -- BaseKnowledgeClient
EpuckKnowledgeRecord -left-o BaseRobotCommsModel
EpuckKnowledgePacket -- BaseRobotCommsModel
EpuckKnowledgePacket -- RobotCommsModel


@enduml
