@startuml

!theme sunlust

!$enable_digital_twin = 0

node "Motion Capture"

node "Centralised Controller PC" as PC {
  component "LocalCommsManager"

  component "Waypoint Controller"

  component "epuck_cpp_driver"

  component "Localiser"

  component "Repartitioner"
}

node "e-puck 0" {
  !if ($enable_digital_twin == 0)
    component "RobotCommsModel" as epuck0RobotCommsModel
    component "UDPKnowledgeServer" as epuck0UDPKnowledgeServer
    component "UDPKnowledgeClient" as epuck0UDPKnowledgeClient
    component "Advanced Sercom v2" as epuck0AdvancedSercom
  !endif
}

node "e-puck 1" {
  !if ($enable_digital_twin == 0)
    component "RobotCommsModel" as epuck1RobotCommsModel
    component "UDPKnowledgeServer" as epuck1UDPKnowledgeServer
    component "UDPKnowledgeClient" as epuck1UDPKnowledgeClient
    component "Advanced Sercom v2" as epuck1AdvancedSercom
  !endif
}

"Motion Capture" <- "e-puck 0": Pose
"Motion Capture" <- "e-puck 1": Pose
"Motion Capture" --> "Localiser": Poses
"Localiser" --> "Waypoint Controller": Pose
"Localiser" --> "LocalCommsManager": Pose
"Repartitioner" --> "Waypoint Controller": Partition
"Waypoint Controller" --> "epuck_cpp_driver": State & Controls
"Repartitioner" <--> "LocalCommsManager": Interactions,\nKnowledge\n& Partitions

' Simplify the diagram by hiding the UDP knowledge server and client connections if the digital twin is disabled
!if ($enable_digital_twin == 0)
  PC -[hidden]-> "e-puck 0"
  PC -[hidden]-> "e-puck 1"
  "e-puck 0" -[hidden]> "e-puck 1"

  "epuck_cpp_driver" <--> epuck0AdvancedSercom: State & Controls
  "epuck_cpp_driver" <--> epuck1AdvancedSercom: State & Controls
  "LocalCommsManager" <--> epuck0RobotCommsModel: Commands,\nHeartbeats\n& Knowledge\n\n\n
  "LocalCommsManager" <--> epuck1RobotCommsModel: Commands,\nHeartbeats\n& Knowledge
  epuck0RobotCommsModel <--> epuck0UDPKnowledgeServer: Knowledge
  epuck0RobotCommsModel <--> epuck0UDPKnowledgeClient: Knowledge
  epuck1RobotCommsModel <--> epuck1UDPKnowledgeClient: Knowledge
  epuck1RobotCommsModel <--> epuck1UDPKnowledgeServer: Knowledge
  epuck0UDPKnowledgeServer <-> epuck1UDPKnowledgeClient: Knowledge
  epuck0UDPKnowledgeClient -[hidden]> epuck0UDPKnowledgeServer
  epuck1UDPKnowledgeClient -[hidden]> epuck1UDPKnowledgeServer
!else
  "epuck_cpp_driver" <-> "e-puck 0": State & Controls
  "epuck_cpp_driver" <-right-> "e-puck 1": State & Controls
  "LocalCommsManager" <-up-> "e-puck 0": Commands,\nHeartbeats\n& Knowledge
  "LocalCommsManager" <-> "e-puck 1": Commands,\nHeartbeats\n& Knowledge
  "e-puck 0" <--> "e-puck 1": Knowledge
!endif



' Only show the Gazebo digital twin if enabled
!if ($enable_digital_twin == 1)
  node "Gazebo Digital Twin" as Gazebo {
    component "LocalCommsManager" as gzLocalCommsManager

    component "Waypoint Controller" as gzWaypointController

    component "Localiser" as gzLocaliser

    component "Repartitioner" as gzRepartitioner

    node "e-puck 0 Model" as simEpuck0 {
      component "RobotCommsModel" as simEpuck0RobotCommsModel
      component "GZKnowledgeServer" as simEpuck0GZKnowledgeServer
      component "GZKnowledgeClient" as simEpuck0GZKnowledgeClient
    }

    node "e-puck 1 Model" as simEpuck1 {
      component "RobotCommsModel" as simEpuck1RobotCommsModel
      component "GZKnowledgeServer" as simEpuck1GZKnowledgeServer
      component "GZKnowledgeClient" as simEpuck1GZKnowledgeClient
    }
  }

  "Waypoint Controller" -up-> Gazebo: State & Controls

  gzLocaliser --> gzWaypointController: Pose
  gzLocaliser --> gzLocalCommsManager: Pose
  gzRepartitioner --> gzWaypointController: Partition
  gzWaypointController --> simEpuck0: State & Controls
  gzWaypointController --> simEpuck1: State & Controls
  gzRepartitioner <--> gzLocalCommsManager: Interactions,\nKnowledge\n& Partitions

  gzLocalCommsManager <--> simEpuck0RobotCommsModel: Heartbeats & Knowledge
  gzLocalCommsManager <--> simEpuck1RobotCommsModel: Heartbeats & Knowledge
  simEpuck0RobotCommsModel <--> simEpuck0GZKnowledgeServer: Knowledge
  simEpuck0RobotCommsModel <--> simEpuck0GZKnowledgeClient: Knowledge
  simEpuck1RobotCommsModel <--> simEpuck1GZKnowledgeClient: Knowledge
  simEpuck1RobotCommsModel <--> simEpuck1GZKnowledgeServer: Knowledge
  simEpuck0GZKnowledgeServer <-> simEpuck1GZKnowledgeClient: Knowledge

  simEpuck0 -[hidden]> simEpuck1
  simEpuck0GZKnowledgeClient -[hidden]> simEpuck0GZKnowledgeServer
  simEpuck1GZKnowledgeClient -[hidden]> simEpuck1GZKnowledgeServer
!endif

@enduml
